### ISSUE TITLE
"Something went wrong when trying to access credentials. Contact support." when running `suitecloud account:setup:ci` from Docker

### ISSUE THREAD

**Issue by akiraquenot-lab** [oracle/netsuite-suitecloud-sdk#838]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud CLI

### Version of the SuiteCloud Tool

2.0.0

### Operating system

amazoncorretto:17-alpine (Docker)

### Node Version / VSCode Version

v20.15.1

### JAVA Version

"17.0.12" 2024-07-16 LTS

### Bug description

The `suitecloud account:setup:ci` command works as expected when executed locally within a Docker container. 
However, when the identical Docker image is built & deployed to Docker Hub and used in my Bitbucket pipeline, the command fails with the error message `Something went wrong when trying to access credentials. Contact support.`

Am I missing something?

### Steps To Reproduce

1. Create `Dockerfile` : 
```
# Use an Alpine base image with Amazon Corretto JDK 17
FROM amazoncorretto:17-alpine

USER root
# Install necessary dependencies and Node.js
RUN apk update && \
    apk add --no-cache curl bash nodejs npm dbus

# Check installed versions
RUN java -version && \
    node -v && \
    npm -v

# Run dbus-uuidgen to generate a UUID
RUN dbus-uuidgen --ensure

# Install the SuiteCloud npm library
RUN npm install -g @oracle/suitecloud-cli --acceptSuiteCloudSDKLicense

# Set the working directory
WORKDIR /app
```

2. Build & Deploy the Dockerfile to Docker Hub with command : 
```
docker build -t --no-cache <myusername>/<imagename>:latest .
docker push <myusername>/<imagename>:latest
```

3. Define `bitbucket-pipelines.yaml` as follow : 
```
image:
    name: <myusername>/<imagename>:latest
    username: $DOCKER_HUB_USERNAME
    password: $DOCKER_HUB_PASSWORD

pipelines:
    branches:
        main:
            - step: &connect-to-sb1
                  name: Connect to SB1
                  script:
                      - cd project
                      - npm install --acceptsuitecloudsdklicense
                      - suitecloud account:setup:ci --account XXXXXXX_SB1 --authid sb1 --certificateid XXXXXXX --domain XXXXXXX-sb1.app.netsuite.com --privatekeypath ../private.pem
```

### Actual Output

Something went wrong when trying to access credentials. Contact support.

### Expected Output

The authentication was successful with the following account and role: XXX [Administrator]. This project will use the authentication ID "sb1" as default.
The account has been successfully set up.
